### ISSUE TITLE
Custom header udx

### ISSUE THREAD

**Issue by Benjamin23** [warappa/OpenTransSharp#22]
We have a specific use case where we receive a XML and should write it as-is in the header udx field. 

In our use case, we generate custom XML that our partners can process and it's delivered in the HEADER_UDX filed. 

The XML we generate is something like this: Note that the COMPANY element is somewhat generic, and can be up to 50 different values. 

`<UDX.COMPANY.Klasse>Prio_5</UDX.COMPANY.Klasse>`

And the expected udx should be something like: 
```
<HEADER_UDX>
  <UDX.COMPANY.Klasse>Prio_5</UDX.COMPANY.Klasse>
</HEADER_UDX>
```

However, if we try to add it to the HeaderUdx list (in our case it's an Order document), the XML get's spaced and transformed like this: 

```
<HEADER_UDX>
        <anyType xsi:type="xsd:string">&lt;UDX.COMPANY.Klasse&gt;Prio_5&lt;/UDX.COMPANY.Klasse&gt;</anyType>
</HEADER_UDX>
```

Is there a way we can pass in custom XML to the HeaderUdx and have it generated as-is? Or, if now, can we expand the library so custom raw XML can be passed in?

**Comment by warappa** [comment]
Hi @Benjamin23,
if `COMPANY` is really generic, then I think you hit a **limitation of .NET's XmlSerializer**.
Either
* write a .NET class with a `XmlRoot` attribute for _every_(!) variant of `COMPANTY` and register them, or
* change the header contract[^1], use a wrapper XML tag and use the `IXmlSerializable` interface (`IXmlSerializable` requires a [wrapper tag](https://learn.microsoft.com/de-de/dotnet/api/system.xml.serialization.ixmlserializable.writexml?view=net-8.0#remarks) unfortunately)

Honestly, I somewhat regret using the old `XmlSerializer` although it's still supported, because I learned there're some things you simply cannot support with it.

I myself am interested if there is a solution for this.

[^1]: With "_change the header contract_" I mean something like this:
    ```xml
    <HEADER_UDX>
      <UDX.COMPANYINFO>
        <Klasse>Prio_5</Klasse>
      </UDX.COMPANYINFO>
    </HEADER_UDX>
    ```

**Comment by Benjamin23** [comment]
@warappa Thanks you for the feedback, we tried different solutions, but ended up refactoring our solution so it is working now.
